ici/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sport.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
]

sport/urls.py
from django.urls import path, re_path
from . import views
from sport.views import PlayerList, Daily_ScanList


urlpatterns = [
    path('', views.home, name='sport-home'),
    path('scanner', views.scanner, name='security-scanner'),
    path('player_list/', PlayerList.as_view(), name='player_list'),
    path('getqrcode/<int:id>/', views.getqrcode, name='getqrcode'),
    path('scanmenow/<int:id>/', views.scanmenow, name='scanmenow'),
    path('daily_scan/', Daily_ScanList.as_view(), name='daily_scan'),
    # path('daily_scan_filter/<str:date>/', views.daily_scan_filter, name='daily_scan_filter'),
    # path('players_filter/', views.players_filter, name='players_filter'),
    # path('test_filter/', views.test_filter, name='test_filter'),
]

sport/models.py
from django.db import models
from django.utils import timezone as u_timezone
from pytz import timezone
from datetime import date, datetime
import barcode
from barcode.writer import ImageWriter
from io import BytesIO
from django.core.files import File
import qrcode
import qrcode.image.svg
import base64
import uuid
import os

def rename_profile_image(instance, filename):
    print('Original file name :::::::::::::: {}'.format(filename))
    new_file_name = '{}-{}.png'.format(instance.first_name, uuid.uuid4())
    print('new file name :::::::::::::: {}'.format(new_file_name))
    return new_file_name

def get_cst_timestamp():
    time_format = "%Y-%m-%d %H:%M:%S %Z%z"
    # Current time in UTC
    now_utc = datetime.now(timezone('UTC'))
    print(now_utc.strftime(time_format))
    # Convert to central America/Chicago time zone
    now_central_timestamp = now_utc.astimezone(timezone('America/Chicago'))
    db_timestamp = now_central_timestamp.strftime(time_format)
    print(db_timestamp)
    return db_timestamp

def get_cst_date():
    date_format = "%Y-%m-%d"
    # Current time in UTC
    now_utc = datetime.now(timezone('UTC'))
    print(now_utc.strftime(date_format))
    # Convert to central America/Chicago time zone
    now_central_date = now_utc.astimezone(timezone('America/Chicago'))
    db_date = now_central_date.strftime(date_format) 
    print(db_date)
    return db_date


class Player(models.Model):
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    mobile = models.BigIntegerField()
    address = models.CharField(max_length=300)
    email = models.EmailField(max_length=250)
    CHOICES = [('Male', 'Male'), ('Female', 'Female')]
    gender = models.CharField(max_length=10, choices=CHOICES, default='Male')
    Q_CHOICES = [('Yes', 'Yes'), ('No', 'No')]
    # plus21 = models.BooleanField(default=False)
    plus21 = models.CharField(max_length=10, choices=Q_CHOICES, default='No')
    date_of_birth = models.DateField(null=True, blank=True)
    vaccinated = models.CharField(max_length=10, choices=Q_CHOICES, default='No')
    # vaccinated = models.BooleanField(default=False)
    emergency_contact_name = models.CharField(max_length=250)
    emergency_contact_phone = models.CharField(max_length=100)
    profile_picture = models.ImageField(default='', upload_to=rename_profile_image)
    registeration_date = models.DateTimeField(default=u_timezone.now)
    qr_code = models.CharField(max_length=20)
    disclaimer = models.BooleanField(default=False)

    def __str__(self):
        return 'ID: ' + str(self.id) + '  :::::  First Name: ' + self.first_name + '  :::::  Last Name: ' + self.last_name + '  :::::  Mobile: ' + str(self.mobile)

    def clean_date_of_birth(self):
        bdate = self.cleaned_data['date_of_birth']
        if self.plus21 == 'on':
            return null
        else:
            return bdate



class Daily_Scan(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    scan_date = models.CharField(max_length=50, default=get_cst_date) 
    scan_timestamp = models.CharField(max_length=100, default=get_cst_timestamp) 
    # scan_date = models.DateField(default=get_cst_date) #date.today)
    # scan_timestamp = models.DateTimeField(default=get_cst_timestamp) #timezone.now)

    def __str__(self):
        return 'ID: ' + str(self.player.id) + '  :::::  First Name: ' + self.player.first_name + '  :::::  Last Name: ' + self.player.last_name + '  :::::  Scan Date: ' + str(self.scan_date)

    

sport/forms.py
from django.forms import ModelForm
from django import forms
from .models import *
from bootstrap_datepicker_plus import DatePickerInput

class PlayerForm(ModelForm):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')  
        super(PlayerForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Player
        # fields = '__all__'
        exclude = ['registeration_date', 'qr_code']        
        widgets = {
            'first_name' : forms.TextInput(attrs={'required': True, 'class': 'form-control'}),
            'last_name' : forms.TextInput(attrs={'required': True, 'class': 'form-control'}),
            'mobile' : forms.TextInput(attrs={'required': True, 'class': 'form-control'}),
            'address' : forms.TextInput(attrs={'required': True, 'class': 'form-control'}),
            'email' : forms.EmailInput(attrs={'required': True, 'class': 'form-control'}),
            'gender' : forms.RadioSelect(attrs={'class': 'form-check form-check-inline'}),
            'plus21' : forms.RadioSelect(attrs={'class': 'form-check form-check-inline'}),
            # 'plus21' : forms.CheckboxInput(attrs={'class' : 'custom-checkbox checkbox-xl', 'required': False}),
            'date_of_birth' : DatePickerInput(format='%m/%d/%Y'),
            # 'date_of_birth' : forms.DateField(required= False, widget=DatePickerInput(format='%m/%d/%Y')),
            'vaccinated' : forms.RadioSelect(attrs={'class': 'form-check form-check-inline'}),
            # 'vaccinated' : forms.CheckboxInput(attrs={'class' : 'custom-checkbox checkbox-xl'}),
            'emergency_contact_name' : forms.TextInput(attrs={'required': True, 'class': 'form-control'}),
            'emergency_contact_phone' : forms.TextInput(attrs={'required': True, 'class': 'form-control'}),
            'profile_picture' : forms.ClearableFileInput(attrs={'required': True, 'class': 'form-control'}),
            'disclaimer' : forms.CheckboxInput(attrs={'required': True, 'class' : 'custom-checkbox checkbox-xl'})
        }

        labels = {
            "plus21" : "Are you 21+ age ? ",
            "vaccinated" : "Are you vaccinated ? ",
            "disclaimer" : "Release of Liability and COVID-19 Related Information (Required)",
            "profile_picture" : "Attach a clear image of your face. Please do not attach avatar image! "
        }   


class ScannerForm(forms.Form):
    ID = forms.CharField(max_length=100, required=True)
     
        

sport/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.views.generic import CreateView
from django.views.generic import ListView
from .forms import PlayerForm
from .forms import ScannerForm
from .models import Player
from .models import Daily_Scan
from django.contrib import messages
from django.core.mail import send_mail, BadHeaderError
from django.conf import settings
import qrcode
import qrcode.image.svg
from io import BytesIO
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
import base64
import time
import pytz
from django.utils import timezone
from datetime import date, datetime
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Q, FilteredRelation
from django.db.models.functions import Lower

def home(request):
    form = PlayerForm()

    if request.method == "POST":
        print(request.POST)
        form = PlayerForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                player = form.save()
                factory = qrcode.image.svg.SvgImage
                qr_text = "{}".format(player.id)
                img = qrcode.make(qr_text, image_factory=factory, box_size=20)
                stream = BytesIO()
                img.save(stream)
                base64_image = base64.b64encode(stream.getvalue()).decode()
                qr = 'data:image/svg+xml;utf8;base64,' + base64_image
                messages.success(request, 'Registration completed successfully!')
                return render(request, 'result.html', {'qr': qr})
                
            except Exception as e:
                print('ERROR  :::::::: {}'.format(e))
                messages.error(request, 'Registration failed! Please try again later.')
        else:
            print('Form is not valid ::::::: {}'.format(form.is_valid()))
            messages.error(request, 'Registration failed! Please try again later.')
    
    context = {'form': form}
    return render(request, 'registration.html', context)


def scanner(request):
    if not request.user.is_authenticated:
        return redirect('/login')
    scannerForm = ScannerForm()
    player = None
    print('Scanner In Progress :::::::::::::::::::')
    if request.method == "POST":
        scannerForm = ScannerForm(request.POST)
        if scannerForm.is_valid():
            try:
                
                playerId = request.POST['ID']
                print(" Scanned ID ::::::::::: {}".format(playerId))
                player = Player.objects.get(id=playerId)
                
                # Create and save player in daliy_scan table
                daily_scan = Daily_Scan.objects.create(player=player)
                print('daily_scan saved successfully ############## ')

            except Exception as e:
                    print('ERROR  :::::::: {}'.format(e))
                    messages.error(request, 'Something went wrong, please make sure Player Id is correct :( ! ', extra_tags='scanner')
        else:
            messages.error(request, 'Value is invalid! ', extra_tags='scanner')
    
    if player is None:
        profile_image = '{}{}'.format(settings.MEDIA_URL, "profile_icon.png")
    else:
        profile_image = '{}{}'.format(settings.MEDIA_URL, player.profile_picture)

    context = {
        'player' : player,
        'scannerForm' : scannerForm,
        'profile_image' : profile_image
    }
    return render(request, 'scanner.html', context)


def getqrcode(request, id=None):
    try:
        print('Generating QR Code for Player  ID :::::  {}'.format(id))
        factory = qrcode.image.svg.SvgImage
        qr_text = "{}".format(id)
        img = qrcode.make(qr_text, image_factory=factory, box_size=20)
        stream = BytesIO()
        img.save(stream)
        base64_image = base64.b64encode(stream.getvalue()).decode()
        qr_code = 'data:image/svg+xml;utf8;base64,' + base64_image
        messages.success(request, 'QR code generated successfully!')
    except Exception as e:
        print('ERROR  :::::::: {}'.format(e))

    context = {
        'qr_code' : qr_code
    }
    return render(request, 'getqrcode.html', context)
                

def scanmenow(request, id=None):
    try:
        print('Scanining Player  ID :::::  {}'.format(id))
        player = Player.objects.get(id=id)
        # Create and save player in daliy_scan table
        # scan_timestamp = models.DateTimeField(default=datetime.now(pytz.timezone('US/Central')))
        # scan_timestamp = datetime.now(pytz.timezone('US/Central')) #pytz.timezone("US/Central")
        # scan_timestamp = datetime.utcnow().replace(tzinfo=pytz.timezone('US/Central')) #(tzinfo=pytz.utc)        
        # u = datetime.utcnow()
        # u = u.replace(tzinfo=pytz.utc)
        # tz = pytz.timezone('US/Central')
        # dt_cst = u.astimezone(tz)
        # scan_timestamp = models.DateTimeField(default=timezone.now)

        daily_scan = Daily_Scan.objects.create(player=player)
        print('Player scanned successfully ############## ')
        messages.success(request, 'Player {} scanned successfully!'.format(player.first_name))
    except Exception as e:
        print('ERROR  :::::::: {}'.format(e))

    return redirect(request.META['HTTP_REFERER'])
    # return render(request)


# def players_filter(request):
#     try:
#         # global players_filter_data
#         players_filter_data = request.GET.get('value', None)
#         request.session['players_filter_data'] = players_filter_data
#         print('players_filter value :::::  {}'.format(request.session.get('players_filter_data')))
#         context = {
#         'players_filter_data' : players_filter_data
#         }
#         # render(request, 'player_list.html', context)
#         return HttpResponse('success')
#     except Exception as e:
#         print('ERROR  :::::::: {}'.format(e))


# def test_filter(request):
#     try:
#         value  = request.session.get('players_filter_data')
#         return HttpResponse(f'players_filter_data : {value}')
#     except Exception as e:
#         print('ERROR  :::::::: {}'.format(e))

# def daily_scan_filter(request, date=None):
#     try:
#         print('daily_scan_filter date :::::  {}'.format(date))
#         global daily_scan_filter_date
#         daily_scan_filter_date = date
#     except Exception as e:
#         print('ERROR  :::::::: {}'.format(e))


def get_cst_date():
    date_format = "%Y-%m-%d"
    # Current time in UTC
    now_utc = datetime.now(timezone('UTC'))
    # Convert to central America/Chicago time zone
    now_central_date = now_utc.astimezone(timezone('America/Chicago'))
    db_date = now_central_date.strftime(date_format) 
    print(f"view daily scan date: {db_date}")
    return db_date


class PlayerList(ListView):
    model = Player
    
    def get_context_data(self, **kwargs):
        context = super(PlayerList, self).get_context_data(**kwargs)
        value = self.request.GET.get('value', None)
        object_list = None
        if value is not None:
            if value == '' or value == ' ':
                print('No filter yet, getting first 20 record')
                object_list = Player.objects.all()[:20]
            else:
                if ' ' in value:
                    print("With Spacessssss !!!!!!")
                    names = value.split()
                    print(f"Filter using session value ::: {value}")
                    object_list = Player.objects.filter(Q(first_name__istartswith=names[0]) \
                    | Q(last_name__istartswith=names[1]) | Q(mobile__istartswith=value))
                else:
                    print("No Spacessssss !!!!!!")
                    print(f"Filter using session value ::: {value}")
                    object_list = Player.objects.filter(Q(first_name__istartswith=value) \
                    | Q(last_name__istartswith=value) | Q(mobile__istartswith=value))

        else:
            value = ''
            print('No filter yet, getting first 20 record')
            object_list = Player.objects.all()[:20]

        player_total_count = Player.objects.count()
        context.update({'value': value})
        context.update({'player_total_count': player_total_count})
        context.update({'object_list': object_list})
        return context

    @method_decorator(login_required(login_url='/login'))
    def dispatch(self, *args, **kwargs):
        return super(PlayerList, self).dispatch(*args, **kwargs)


class Daily_ScanList(ListView):
    model = Daily_Scan

    def get_context_data(self, **kwargs):
        context = super(Daily_ScanList, self).get_context_data(**kwargs)
        value = self.request.GET.get('value', None)
        object_list = None
        count = ''
        if value is not None:
            if value == '' or value == ' ':
                print('Filter is empty, getting first 15 record')
                object_list = Daily_Scan.objects.order_by('-scan_date')[:15]
                count = len(object_list)
            else:
                print(f"Filter using session value ::: {value}")
                object_list = Daily_Scan.objects.filter(Q(scan_date__istartswith=value))
                count = len(object_list)
        else:
            value = ''
            print('No filter yet, getting first 15 record')
            object_list = Daily_Scan.objects.order_by('-scan_date')[:15]
            count = len(object_list)

        context.update({'filter_date': value})
        context.update({'count': count})
        context.update({'object_list': object_list})
        return context

    @method_decorator(login_required(login_url='/login'))
    def dispatch(self, *args, **kwargs):
        return super(Daily_ScanList, self).dispatch(*args, **kwargs)  



# plus21 = request.POST.get('plus21', False)
# print('plus21 :::::: {}'.format(plus21))

sport/templates/getqrcode.html
{% extends "main.html" %}
{% block title %} QR Code {% endblock %}
{% block content %}


<div class="container-fluid p-0">
    <div class="alert alert-success alert-dismissible" role="alert" >
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        Please take screenshot and save the QR code on your device, because you are going to use it to enter the ICI MPH.
    </div>
</div>

<br/>

<div class="input-group mb-3">
    <div style="margin: auto">
        <img
            src="{{qr_code|safe}}"
            class="img-fluid shadow-2-strong"
            alt=""
        />
    </div>
    <br/>
  </div>


{% endblock %}

sport/templates/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}

    <meta charset="utf-8"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css" type="text/css" media="all" rel="stylesheet">
    {{ form.media }}  
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>{% block title %} {% endblock %}</title>
    <style >
        input[type=checkbox] {
            transform: scale(1.5);
        }
        label[for="id_vaccinated"]{
            font-weight: bold;
        }
        label[for="id_disclaimer"]{
            font-weight: bold;
        }
        label[for="id_plus21"]{
            font-weight: bold;
        }
        ul {
            list-style-type: none;
        }
        ul li {
            padding: 10px;
        }
    </style>
</head>

<body>

    <div class="container">
        {% block content %} 
        {% endblock %}
    </div>


    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript" src="//cdn.rawgit.com/monim67/django-bootstrap-datepicker-plus/master/bootstrap_datepicker_plus/static/bootstrap_datepicker_plus/js/datepicker-widget.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> -->
    <!-- <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script> -->
    
    <script type="text/javascript">
        $(function () {
            // $('#datetimepicker1').datetimepicker();

            // $("#id_plus21").click(function () {
            //     if ($(this).is(":checked")) {
            //         $('.date').hide();
            //         $('#id_date_of_birth').prop('required', false);
            //         $('#id_date_of_birth').val('01/01/1950');
            //         $('label[for="id_date_of_birth"]').hide();
            //     } else {
            //         $('.date').show();
            //         $('#id_date_of_birth').val('');
            //         $('#id_date_of_birth').prop('required', true);
            //         $('label[for="id_date_of_birth"]').show();
            //     }
            // });

            $('input:radio[name=plus21]').click(function(){
                var inputValue = $(this).attr("value");
                if (inputValue == "Yes"){
                    console.log("Radio buttong YES value is :::::: " + inputValue);
                    $('.date').hide();
                    $('#id_date_of_birth').prop('required', false);
                    $('#id_date_of_birth').val('01/01/1950');
                    $('label[for="id_date_of_birth"]').hide();
                }else{
                    console.log("Radio buttong NO value is :::::: " + inputValue);
                    $('.date').show();
                    $('#id_date_of_birth').val('');
                    $('#id_date_of_birth').prop('required', true);
                    $('label[for="id_date_of_birth"]').show();
                }
            });
        
        });
        
     </script>

</body>

</html>

sport/templates/registration.html
{% extends "main.html" %}
{% block title %} ICI Registration {% endblock %}
{% block content %}

<div class="p-5 text-center">
    <img src="https://irvingmasjid.org/wp-content/uploads/2021/05/cropped-ICI-Logo.png" width="200" height="100" class="d-inline-block align-top" alt="">
    <h3 class="mb-2">MPH Registration Form</h3>
</div>

<div class="form-group">
    {% if messages %}
        {% for message in messages %}
            <div class="container-fluid p-0">
                <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            </div>
        {% endfor %}
    {% endif %}
    <label><u>*All inputs are required*</u></label><br/>
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        •        I release and forever discharge and hold harmless the Islamic Center of Irving (ICI) and its successors from any and all liability, claims, and demands of whatever kind of nature, either in law or in equity, which arise or may hereafter arise.  I understand and acknowledge that this Release discharges ICI from any liability or claim that I may have against ICI with respect to bodily injury, personal injury, illness, death, dismemberment, or property damage that may result from my presence or exposure to COVID-19 that may occur while I am on the premises of ICI.

        <br/><br/><br/>
        <button type="submit" class="btn btn-primary">Register</button>
    <br/><br/><br/>
</form>
</div>


{% endblock %}

sport/templates/result.html
{% extends "main.html" %}
{% block title %} Registration Result {% endblock %}
{% block content %}

{% if messages %}
        {% for message in messages %}
            <div class="container-fluid p-0">
                <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            </div>
        {% endfor %}
{% endif %}

<br/>

<div class="input-group mb-3">
    <div style="margin: auto">
      <!-- {{ qr|safe }} -->
      <img
        src="{{qr|safe}}"
        class="img-fluid shadow-2-strong"
        alt=""
      />
    </div>
   

    <br/>
    <div class="container-fluid p-0">
        <div class="alert alert-warning alert-dismissible" role="alert" >
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            Please take screenshot and save the QR code on your device, because you are going to use it to enter the ICI MPH.
        </div>
    </div>
  </div>

<br/>
<h4><a href = "/">Go back to home page</a></h4>

{% endblock %}

sport/templates/scanner.html
{% extends "main.html" %}
{% block title %} Scanner {% endblock %}
{% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li>
            <img src="https://irvingmasjid.org/wp-content/uploads/2021/05/cropped-ICI-Logo.png" width="100" height="50" class="d-inline-block align-top" alt="">
        </li>
        <li class="nav-item active">
            &emsp;&emsp;&emsp;
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/" target="_blank">ICI Registration</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/scanner">ICI Scanner</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/player_list">All Players</a>
        </li>
        {% if user.is_authenticated %}
            {% if user.get_username == 'aabdelmohsen' or user.get_username == 's_amer' or user.get_username == 'md_mamoon' %}
                <li class="nav-item">
                    <a class="nav-link" href="/daily_scan">Daily Scan</a>
                </li>
            {% endif %}
        {% endif %}
      </ul>

      <a class="nav-link" href="/logout">Logout</a>
    </div>
</nav>

{% if messages %}
        {% for message in messages %}
            {%if "scanner" in message.tags %}
                <div class="container-fluid p-0">
                    <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        {{ message }}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
{% endif %}

<div class="input-group mb-3">
    <div style="margin: auto">
        <form method="POST" name="myform" id="myform" >
            {% csrf_token %}
            {{ scannerForm.as_p }}
        </form>
        <br/>
</div>


<div class="container justify-content-center">

    <div class="row justify-content-md-center">
        <div class="col-4">
            <br/><br/>
            <label style="font-weight: bold;">First Name: </label> &emsp; <label>{{ player.first_name }}</label> 
            <br/><br/><br/>
            <label style="font-weight: bold;">Last Name: </label> &emsp; <label>{{ player.last_name }}</label>     
        </div>
        <div class="col-6">
            <img src="{{ profile_image }}" class="rounded" width="304" height="236"/>
        </div>
    </div>

    <div class="row">
        <div class="col-5">
            <br/>
            <h6><a href = "/">&emsp;&emsp; Go back to home page</a></h6>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>

<script type="text/javascript">

    $(function() {
        console.log( "ready!" );
        $("input:text").val("");
        $('#id_ID').focus(); 

    });

    function validate_then_submit() {
        var valid = false;
        if (valid == true) {
            document.forms['myform'].submit();
        }
    }   
</script>

{% endblock %}